### ISSUE TITLE
Why are parameters like ROS_IP global?

### ISSUE THREAD

**Issue by StephanHasler** [Unity-Technologies/ROS-TCP-Endpoint#115]
https://github.com/Unity-Technologies/ROS-TCP-Endpoint/blob/715a402ec09ce8095faabed915e3371638b4246a/src/ros_tcp_endpoint/server.py#L48
ROS_IP and ROS_TCP_PORT are global ROS parameters.
So they are expected to be set directly as /ROS_IP.
I think it would be cleaner if these parameters were privat/local.
In this way the global ROS workspace would not be polluted.
Other nodes might like to have a different ROS_IP and then they would be in conflict.

Maybe also the ROS in the names ROS_IP and ROS_TCP_PORT is misleading.
Because it is the IP and PORT where somebody else from outside can connect to over TCP and not with ROS, or?

**Comment by at669** [comment]
Hi, thanks for the post! I’ve created an internal ticket to investigate the type resolution for the networking parameters. 

With regards to the parameter names, the `ROS` prefix is intended to differentiate the machine running the ROS endpoint (which has the ROS_IP and _PORT) from the machine running Unity, to clarify that the IP and port values being set on the "Unity side" are to be the values of the machine on the "ROS side."

[Ticket#: AIRO-1617]

**Comment by StephanHasler** [comment]
Is there some progress on the internal ticket?

**Comment by at669** [comment]
Hi, sorry for the delay--we'll comment in the thread when there's an update. If you have a workaround or have made these changes locally, please feel free to open a pull request for changing the name resolution.

**Comment by mrpropellers** [comment]
Ok, so it seems like all that's needed here is to eliminate the preceding "/" character? I can rename the variable to something that more accurately reflects its intended use, as well.

**Comment by StephanHasler** [comment]
I would make it a private parameter like ~ROS_IP.

Given two ros_tc_endpoint nodes in a namespace /foo (or the global one /)
/foo/endpoint_1
/foo/endpoint_2
the resolved parameter names would be in the private case (~ROS_IP):
/foo/endpoint_1/ROS_IP
/foo/endpoint_2/ROS_IP
and in the relative case (ROS_IP)
/foo/ROS_IP
/foo/ROS_IP
At least this is what I conclude from:
http://wiki.ros.org/Names
So there would be again a conflict for the relative case, unless you put the nodes into different namespaces.

I think you would use a relative parameter when it must be shared among several nodes in a namespace.
If the endpoint is the only node that needs to know about the particular ROS_IP than a private parameter is a good choice.

**Comment by StephanHasler** [comment]
Regarding the naming, I would avoid using ROS in the names of the parameter.
I would name the parameters like the variables in the code:
self.tcp_ip = rospy.get_param("~TCP_IP")
self.tcp_port = rospy.get_param("~TCP_PORT", 10000)
Because then the overall naming is very consistent:

Also following:
http://wiki.ros.org/ROS/EnvironmentVariables
ROS_IP is somehow a reserved environment variable name.

**Comment by StephanHasler** [comment]
A problem might also be how you initialize the node in the default_server_endpoint.py.
It is quite uncommon to set a node's name by a parameter (here /TCP_NODE_NAME).
And I guess no one ever used that parameter, as it is also not used in the endpoint.launch.
Also the launch file assigns the name 'server_endpoint" to the node while the default /TCP_NODE_NAME is TCPServer.
This is quite confusing and also might conflict with the ROS namespacing.

More common way would be: 
```python
def main():
    # Start the Server Endpoint
    rospy.init_node("tcp_server", anonymous=True)
    tcp_server = TcpServer(rospy.get_name())
    tcp_server.start()
    rospy.spin()
```
So 'tcp_server' would be the default name of the node which can be overridden by the launch file.
(or tcp_bridge might also be a better name than server_endpoint)

Furthermore TcpServer does not make use of the node's name, except for storing it.
I would remove node_name from the TcpServer code.

So this would give:
```python
def main():
    # Start the Server Endpoint
    rospy.init_node("tcp_server", anonymous=True)
    tcp_server = TcpServer()
    tcp_server.start()
    rospy.spin()
```

**Comment by StephanHasler** [comment]
The endpoint.launch would look like:
```xml
<launch>
    <arg name="tcp_ip" default="127.0.0.1"/>
    <arg name="tcp_port" default="10000"/>

    <node name="tcp_server" pkg="ros_tcp_endpoint" type="default_server_endpoint.py" args="--wait" output="screen" respawn="true">
        <param name="tcp_ip" value="$(arg input_topic)"/>
        <param name="tcp_port" value="$(arg target_frame)"/>
    </node>
</launch>
```

**Comment by StephanHasler** [comment]
While checking in how far node_name is used inside TcpServer, I stumbled over test_server.py.
There are many lines like:
```python
mock_import_module.assert_called_once
```
Pycharm tells me that these lines would have no effect. And I guess it is right. It should be a function call:
```python
mock_import_module.assert_called_once()
```
Also test_thread_pauser.py has the same problem.

I know I should better make a new issue for this :)

**Comment by mrpropellers** [comment]
Yes, if you have a fix already that supports your use case feel free to submit a pull request! There is always more work to be done on our code, but it needs to be prioritized against all our other feature and support work, so naming issues and other low-impact fixes tend to stay un-resolved until we have proof they're causing problems. You'll need to make the PR against `dev-ros` or `dev-ros2` depending on which version of ROS you are using. I can port the relevant changes to the other branch once the initial merge is resolved.

**Comment by StephanHasler** [comment]
I have a question on how to do the PR. I guess the required steps are:
1. Push my changes as a new topic branch.
2. Create a pull request using that branch.

However, somehow I'm not able to push my branch to you. The command line says:
>git push --set-upstream origin stephan/called_once
remote: Permission to Unity-Technologies/ROS-TCP-Endpoint.git denied to StephanHasler.
fatal: unable to access 'https://github.com/Unity-Technologies/ROS-TCP-Endpoint.git/': The requested URL returned error: 403

I'm using a personal access token for authentication. Do I need to authorize this token? Or do I need any other kind of permission from your side first?
