### ISSUE TITLE
ROS 2 Support Planned?

### ISSUE THREAD

**Issue by maxlein** [Unity-Technologies/ROS-TCP-Endpoint#12]
Hi, 

is there any ROS 2 support planned in the near future?

**Comment by LaurieCheers-unity** [comment]
Hi there. We definitely want to support ROS 2 at some point. If you can tell us more about your use case, it could help us to prioritize it. Thanks!

**Comment by maxlein** [comment]
We are running the navigation stack and are simulating a warehouse in unity with robots driving around.  
Currently we use https://github.com/siemens/ros-sharp over websockets but it has some reliability issues.

**Comment by adamwtow** [comment]
Also interested in ROS 2 support. Looking for an alternative to Gazebo for pick and place applications.

**Comment by alvgaona** [comment]
I'm also interested in having a ROS2 version. I've started a branch to set up the folder structure and  `ament_python` rather than `catkin`. Still figuring out a few issues.

**Comment by mpinol** [comment]
We are currently accepting sign ups to alpha test our ROS2 integration if anyone would like to sign up, https://github.com/Unity-Technologies/Unity-Robotics-Hub#new-ros-2 .
