### ISSUE TITLE
Docker container memory usage increases with time, possible memory leak

### ISSUE THREAD

**Issue by mikkomcmenamin** [Unity-Technologies/ROS-TCP-Endpoint#124]
**Describe the bug**
When the Unity client connects, and starts subscribing to a ROS2 topic, the ROS-TCP-ENDPOINT docker container memory usage starts to go up. Container memory usage increases only if the client is connected and the topic is being subscibed to. Once the client disconnects or there is no more ros2 messages being published, the memory usage stays the same. 

**Console logs / stack traces**
No errors or anything out of the ordinary in either ROS-TCP-Endpoint or ROS-TCP-Connector logs. 

**Expected behavior**
Container memory usage should not increase with time 

**Screenshots**
![image (3)](https://user-images.githubusercontent.com/18258308/150340741-cee12114-b1b6-406c-9ef4-259d93663ac1.png)

**Environment:**
- Unity Version: Unity 2021.1.17f1
- Unity machine OS + version: Windows 11, Windows 10 & Android 11
- ROS machine OS + version: Ubuntu 20.04 ROS Foxy 
- ROS–Unity communication: Docker (Running on either Ubuntu 20.04 host or Windows 11 host) 
- ROS-TCP-Connector version: both v0.6.0 and v. 0.5.0
- ROS-TCP-Endpoint branch: both dev-ros2 and main-ros2

**Additional context**
Used msg packages: ros built-in messages, geographic_msgs, unique_identifier_msgs, and a custom message type. 
Only 1 topic.

**Comment by iqbaljunaid** [comment]
Did some profiling. Here is a docker profiling docker log. The
[as-ros-to-unity-profiling-log.zip](https://github.com/Unity-Technologies/ROS-TCP-Endpoint/files/7925176/as-ros-to-unity-profiling-log.zip)
![as-ros-to-Unity-profle](https://user-images.githubusercontent.com/6773830/150775685-4506b2f8-9113-4ffd-a22b-c706982d6ca2.png)

**Comment by hyounesy** [comment]
Thanks for reporting the issue and the detailed information. We created a ticket to investigate the issue [AIRO-1686]

**Comment by mikkomcmenamin** [comment]
Hi! Any updates on this issue?

**Comment by mikkomcmenamin** [comment]
It seems this issue can be resolved by changing ros2 version from Foxy to Galactic. The problem seems to be in Foxy rclpy serialization.

**Comment by mqt0029** [comment]
Seeing similar behavior in ROS Noetic on Docker container.
