### ISSUE TITLE
Directory structure is a bit weird

### ISSUE THREAD

**Issue by alvgaona** [Unity-Technologies/ROS-TCP-Endpoint#17]
# Directory structure is a bit weird

As far as I can see this repository is meant to have a ROS package for other projects (catkin workspaces) to import. In general, I've seen that packages have got to have the following structured define in this [link](http://docs.ros.org/en/independent/api/rospkg/html/packages.html#common-files-and-directories).

Right now, the `tcp_endpoint` package is a little weird, where within [src](https://github.com/Unity-Technologies/ROS-TCP-Endpoint/tree/main/tcp_endpoint/src) we can find "duplicated" files in a wrong location. These files are:

1. `CMakeLists.txt`
2. `package.xml`
3. `setup.py`

Are these files in there for any special reason? It seems to me that those are unused by ROS and they could be safely deleted.

**Comment by alvgaona** [comment]
I'd be glad to add a PR if this seems reasonable. :smile:

**Comment by at669** [comment]
Hi @alvgaona! This has been resolved on our [`dev`](https://github.com/Unity-Technologies/ROS-TCP-Endpoint/tree/dev) branch and will be moving to `main` soon.

Thanks!

**Comment by alvgaona** [comment]
Thanks!
