### ISSUE TITLE
Handle socket timeout exception

### ISSUE THREAD

**Issue by garycoding** [Unity-Technologies/ROS-TCP-Endpoint#18]
Hello,

I've been using this for a couple of weeks now and it's great. Thank you. :)

Just one thing I'd like to add. If I'm not running my Unity game for too long then the socket in here times out and it crashes.

If we just put a try/except around the code in [RosTCPServer.py](https://github.com/Unity-Technologies/ROS-TCP-Endpoint/blob/main/tcp_endpoint/src/tcp_endpoint/RosTCPServer.py) (lines 53-59) like this then it'll stop crashing on timeout.

```
        while True:
            tcp_server.listen(self.connections)

            try:
                (conn, (ip, port)) = tcp_server.accept()
                new_thread = ClientThread(conn, self, ip, port)
                new_thread.start()
                threads.append(new_thread)
            except socket.timeout as err:
                logging.exception("RosTCPServer: socket timeout")
```

**Comment by LaurieCheers-unity** [comment]
Thanks! I'll add this.

**Comment by LaurieCheers-unity** [comment]
This fix is now in dev branch, will be merged into main soon.
