### ISSUE TITLE
CameraInfo Serialisation Bug

### ISSUE THREAD

**Issue by P3TE** [Unity-Technologies/ROS-TCP-Endpoint#23]
When sending a CameraInfo message to ROS, I've found it doesn't serialise and deserialise correctly.
The issue is that a number of the arrays are defined as fixed length in ROS but when Unity Serialises them, it serialises the length of the array which then displaces the double value deserialisation by 32 bits.
There's an easy fix, just comment out a couple of lines:

`
CameraInfo.cs:178

            //listOfSerializations.Add(BitConverter.GetBytes(K.Length));
            foreach(var entry in K)
                listOfSerializations.Add(BitConverter.GetBytes(entry));
            
            //listOfSerializations.Add(BitConverter.GetBytes(R.Length));
            foreach(var entry in R)
                listOfSerializations.Add(BitConverter.GetBytes(entry));
            
            //listOfSerializations.Add(BitConverter.GetBytes(P.Length));
            foreach(var entry in P)
                listOfSerializations.Add(BitConverter.GetBytes(entry));

`

Also I haven't verified, but I think the following lines should also be changed to this:

`
CameraInfo.cs:217

            var KArrayLength = 9;
            //offset += 4;
            this.K= new double[KArrayLength];
            for(var i =0; i <KArrayLength; i++)
            {
                this.K[i] = BitConverter.ToDouble(data, offset);
                offset += 8;
            }
            
            var RArrayLength = 9;
            //offset += 4;
            this.R= new double[RArrayLength];
            for(var i =0; i <RArrayLength; i++)
            {
                this.R[i] = BitConverter.ToDouble(data, offset);
                offset += 8;
            }
            
            var PArrayLength = 12;
            //offset += 4;
            this.P= new double[PArrayLength];
            for(var i =0; i <PArrayLength; i++)
            {
                this.P[i] = BitConverter.ToDouble(data, offset);
                offset += 8;
            }

`

I think this would be an issue with the Message generation so I guess that code should be updated because it could affect other ROS messages also.

**Comment by at669** [comment]
Hi @P3TE, this issue has been resolved in MessageParser.cs and the generated C# scripts on our `dev` branch and will be merged to `main` soon! You can check out the resolution in Unity-Technologies/ROS-TCP-Connector#21. You may want to checkout `dev` in the meantime to continue development, or wait until Unity-Technologies/ROS-TCP-Connector#32 is merged.

**Comment by at669** [comment]
@P3TE--update, this fix has just been merged into `main`. Feel free to update your packages, try it out and let us know if it resolves your issue!

**Comment by at669** [comment]
Hi @P3TE, I will close out this issue as it has been resolved. Please feel free to open a new issue if another problem arises. Thanks!
