### ISSUE TITLE
Importing ROS-TCP-Connector from git URL in Package Manager results in package not found.

### ISSUE THREAD

**Issue by miwalker** [Unity-Technologies/ROS-TCP-Endpoint#35]
I am using Unity 2020.2.1f1 and using the following URL as directed here (https://github.com/Unity-Technologies/Unity-Robotics-Hub/blob/dev/tutorials/quick_setup.md): https://github.com/Unity-Technologies/ROS-TCP-Connector.git

[Package Manager Window] Cannot perform upm operation: Unable to add package [https://github.com/Unity-Technologies/ROS-TCP-Endpoint.git]: [https://github.com/Unity-Technologies/ROS-TCP-Endpoint.git] does not point to a valid package repository. No package manifest was found. Verify the repository URL and make sure the package is located in the root folder of the repository. [NotFound]. UnityEditor.EditorApplication:Internal_CallUpdateFunctions ()

-----------------------

Please note, adding the URDF-Importer through the same method worked without issue: https://github.com/Unity-Technologies/URDF-Importer.git

**Comment by at669** [comment]
Hi @miwalker,

The development branches of our repositories are going under a bit of an overhaul, we apologize for the dust! These issues will be resolved soon.

package.json is now located under [com.unity.robotics.ros-tcp-connector/package.json](https://github.com/Unity-Technologies/ROS-TCP-Connector/blob/dev/com.unity.robotics.ros-tcp-connector/package.json) on the `dev` branch. However, we recommended using the latest release (v0.1.2) for the most stable version, using `https://github.com/Unity-Technologies/ROS-TCP-Connector.git#v0.1.2`.

Please check out [this issue](https://github.com/Unity-Technologies/ROS-TCP-Connector/issues/58) on the TCP Connector repo for more information on if you would like to use the `dev` branch for development.

Let me know if these options resolve your issue. Thanks!

**Comment by miwalker** [comment]
That worked! Thank you for the prompt reply as well - very much appreciated. 

Keep up the good work guys, this official robotics support is incredible.
